name: Docker Build Test

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test-docker-build:
    name: Test Docker Builds
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        component: [backend, frontend]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Backend Docker image
      if: matrix.component == 'backend'
      uses: docker/build-push-action@v5
      with:
        context: ./src/be
        file: ./src/be/Dockerfile
        push: false
        tags: hoptranscribe-be:test
        
    - name: Build Frontend Docker image
      if: matrix.component == 'frontend'
      uses: docker/build-push-action@v5
      with:
        context: ./src/fe
        file: ./src/fe/Dockerfile
        push: false
        tags: hoptranscribe-fe:test
